# Generated by Django 6.0.3 on 2026-04-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('Water', 'Water'), ('Electricity', 'Electricity'), ('Roads', 'Roads')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
